version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
